### ISSUE TITLE
Crash when bribing villager

### ISSUE THREAD

**Issue by myyka** [Elmartino4/high-level-enchants#10]
When right clicking villager with Gold Ingot or Gold Block in hand game crashes.

Minecraft 1.18.2

java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.HashMap.get(Object)" is null
	at com.github.Elmartino4.highLevelEnchants.BribeVillager.selectBookTrade(BribeVillager.java:90) ~[high-level-enchants-1.0.0-1.18.1.jar:?]
	at com.github.Elmartino4.highLevelEnchants.BribeVillager.<init>(BribeVillager.java:45) ~[high-level-enchants-1.0.0-1.18.1.jar:?]
	at net.minecraft.class_1646.handler$znm000$injectInteractMob(class_1646.java:1671) ~[server-intermediary.jar:?]
	at net.minecraft.class_1646.method_5992(class_1646.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_1308.method_5688(class_1308.java:1131) ~[server-intermediary.jar:?]
	at net.minecraft.class_1657.method_7287(class_1657.java:1070) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244$1.method_33897(class_3244.java:1342) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244$1.method_34219(class_3244.java:1353) ~[server-intermediary.jar:?]
	at net.minecraft.class_2824$class_5909.method_34213(class_2824.java:116) ~[server-intermediary.jar:?]
	at net.minecraft.class_2824.method_34209(class_2824.java:66) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_12062(class_3244.java:1339) ~[server-intermediary.jar:?]
	at net.minecraft.class_2824.method_12251(class_2824.java:53) ~[server-intermediary.jar:?]
	at net.minecraft.class_2824.method_11054(class_2824.java:13) ~[server-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:808) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:790) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:784) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:769) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zbe000$modifiedRunLoop(MinecraftServer.java:2905) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by Elmartino4** [comment]
I'm unsure about the cause of the crash.
Could you please clarify which trades the villager currently offers, and whether you have any other mods installed.

**Comment by myyka** [comment]
I did some testing

It happens on every set of trade offers even when librarian does not have enchanted book and on every villager mastery.
If I hold a gold ingot or gold block in my main hand and right click on a villager it crashes.

I did not have any additional mods installed only:
    high-level-enchants-1.0.0-1.18.1
    fabric-api-0.54.0+1.18.2
    fabric loader version: 0.14.6 

I also tested on new world in 1.18.1 with following:
    high-level-enchants-1.0.0-1.18.1
    fabric-api-0.46.6+1.18
    fabric loader version: 0.14.6 
and crash is still happening.

**Comment by myyka** [comment]
I tried to change some things

It seems that the config file enchantment names do not match.

e.g. 
in config it is "minecraft:efficiency" but in BribeVillager.java line 90 next.getTranslationKey() returns "enchantment.minecraft.efficiency" and I can see that the ConfigInstance was changed to use "minecraft:xyz"but BribeVillager.java was not updated

After reverting ConfigInstance crash is not happening anymore but now it doesn't opet villager GUI and in BribeVillager.java function doBribe prints "no trades found"
